'use client';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout, Menu, theme } from 'antd';

const { Header, Content, Footer } = Layout;

const inter = Inter({ subsets: ['latin'] });

const items = [
  {
    key: 'home',
    label: 'الرئيسية',
  },
  {
    key: 'patients',
    label: 'المرضى',
  },
  {
    key: 'decisions',
    label: 'القرارات',
  },
];

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Layout>
            <Header style={{ display: 'flex', alignItems: 'center' }}>
              {/* <div className="demo-logo"> الرئيسية</div> */}
              <Menu
                theme="dark"
                mode="horizontal"
                defaultSelectedKeys={['2']}
                items={items}
                style={{ flex: 1, minWidth: 0 }}
              />
            </Header>
            <Content style={{ padding: '0 48px' }}>
              <div
                style={{
                  background: colorBgContainer,
                  minHeight: 280,
                  padding: 24,
                  borderRadius: borderRadiusLG,
                }}
              >
                {children}
              </div>
            </Content>
            <Footer style={{ textAlign: 'center' }}>
              Hospital management system ©{new Date().getFullYear()}.
            </Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
